AQI-3142 SDK: Updated Configurations SDK to include new parameter for TwinTypeId
AquaticInformatics/aquarius-one-sdk pull request #16
Opened 2022-07-11 22:57 UTC by DarshanaGandhi-AI

2022-07-12 13:17 UTC, AQI-DanG requested changes
I think we also need a version number change with this

2022-07-12 16:58 UTC, AQI-DanG approved these changes

2022-07-12 17:48 UTC, JonathanRobertson-AQI approved these changes

2022-07-19 16:04 UTC, JonathanRobertson-AQI approved these changes

2022-07-19 16:04 UTC, merged